# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookSearch', '0002_auto_20170316_0524'),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('loan_id', models.AutoField(db_column='loan_id', primary_key=True, serialize=False)),
                ('date_out', models.DateField(db_column='date_out')),
                ('due_date', models.DateField(db_column='due_date')),
                ('date_in', models.DateField(db_column='date_in', null=True)),
            ],
            options={
                'db_table': 'book_loans',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('loan', models.OneToOneField(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fines', serialize=False, to='bookLoans.BookLoan')),
                ('fine_amt', models.DecimalField(db_column='fine_amt', decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField(db_column='paid', default=False)),
            ],
            options={
                'db_table': 'fines',
            },
        ),
        migrations.AddField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, related_name='loaners', to='bookSearch.Book'),
        ),
        migrations.AddField(
            model_name='bookloan',
            name='borrower',
            field=models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='borrowers.Borrower'),
        ),
        migrations.RunSQL(
            "ALTER TABLE book_loans ADD CONSTRAINT due_date_check_constraint CHECK (due_date > date_out);",
            "ALTER TABLE book_loans DROP CONSTRAINT due_date_check_constraint"
        ),
        migrations.RunSQL(
            "ALTER TABLE book_loans ADD CONSTRAINT date_in_check_constraint CHECK (date_in IS NULL OR date_in >= date_out);",
            "ALTER TABLE book_loans DROP CONSTRAINT date_in_check_constraint"
        )
    ]
