# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookLoans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='date_in',
            field=models.DateField(blank=True, db_column='date_in', null=True),
        ),
    ]
