# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(db_column='author_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(db_column='isbn', max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=250, null=True)),
                ('cover_link', models.CharField(db_column='cover_link', max_length=100, null=True)),
                ('pages', models.IntegerField(db_column='pages', null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='bookSearch.Author')),
                ('book', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, to='bookSearch.Book')),
            ],
            options={
                'db_table': 'book_authors',
            },
        ),
        migrations.CreateModel(
            name='BookPublisher',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('book', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, to='bookSearch.Book')),
            ],
            options={
                'db_table': 'book_publishers',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(db_column='publisher_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
            ],
            options={
                'db_table': 'publishers',
            },
        ),
        migrations.AddField(
            model_name='bookpublisher',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.CASCADE, to='bookSearch.Publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='bookpublisher',
            unique_together=set([('book', 'publisher')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together=set([('book', 'author')]),
        ),
        migrations.RunSQL(
            "ALTER TABLE book ADD CONSTRAINT isbn_len_check CHECK (char_length(isbn) = 10);",
            "ALTER TABLE book DROP CONSTRAINT isbn_len_check"
        )
    ]
