# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookSearch.Author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='bookSearch.Book'),
        ),
        migrations.AlterField(
            model_name='bookpublisher',
            name='book',
            field=models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='bookSearch.Book'),
        ),
        migrations.AlterField(
            model_name='bookpublisher',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookSearch.Publisher'),
        ),
    ]
